# Site Build Settings

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Tell Jekyll to also look in the pages/ folder
include:             [pages]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:               "TrEnCh Project"
description:         "Tools for TRanslating ENvironmental CHange into organismal responses"
author:              "Buckley Lab, University of Washington"

# Set the baseurl to your repository name if publishing to https://<user>.github.io/<repo>/
# e.g. baseurl: "/trenchproject"  (leave empty "" for a user/organization or custom-domain site)
baseurl:             ""

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
