title: TrEnCh Project
description: >-
  Tools for TRanslating ENvironmental CHange into organismal responses.
  We provide computational and visualization tools that translate coarse air
  temperature models into fine-scale predictors of how animals and ecosystems
  respond to climate change.
url: "https://trenchproject.github.io"
baseurl: ""

remote_theme: LeNPaul/Millennial

navigation:
  - title: The Science
    url: /the-science/
  - title: Case Studies
    url: /case-studies/
  - title: Tools
    url: /tools/
  - title: About the Project
    url: /about/
  - title: Latest News
    url: /news/

footer-links:
  github: trenchproject
  instagram: trenchproject

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock