title: "The TrEnCh Project"
GAID: UA-85523275-1 

include:
  - "_pages"

gems: ["jekyll-sitemap", "jekyll-paginate"]

sass:
  sass_dir: assets/scss

# blog settings
permalink: /news/:title
paginate_path: /news/page-:num"
paginate: 10