title: TrEnCh Project
description: >-
  Tools for TRanslating ENvironmental CHange into organismal responses.
  We provide computational and visualization tools that translate coarse air
  temperature models into fine-scale predictors of how animals and ecosystems
  respond to climate change.
url: "https://trenchproject.github.io"
baseurl: ""

remote_theme: LeNPaul/Millennial

navigation:
  - title: The Science
    url: /pages/science/
  - title: Case Studies
    url: /pages/case-studies/
  - title: Tools
    url: /pages/tools/
  - title: About the Project
    url: /pages/about/
  - title: Latest News
    url: /pages/news/

footer-links:
  github: trenchproject
  instagram: trenchproject

markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
