# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'The Science',      url: 'the-science'}
- {name: 'Infrared Imagery', url: 'infrared-modeling'}
- {name: 'Case Studies',     url: 'case-studies'}
- {name: 'Butterfly',        url: 'butterfly'}
- {name: 'Grasshopper',      url: 'grasshopper'}
- {name: 'Tools',            url: 'tools'}
- {name: 'About',            url: 'about'}
- {name: 'Latest News',      url: 'latest-news'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: 'https://www.instagram.com/trenchproject/'}
- {icon: 'github',    link: 'https://github.com/trenchproject'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
